google/CFU-Playground

README.md
Signed-off-by: Michael Gielda <mgielda@antmicro.com>
=> Link to Renode + use uppercase

common/Makefile
Add source and line numbers to generated disassembly file.
=> common/Makefile: add source to disassembly

soc/arty.mk
It prevents "make prog" from executing.
Can be disabled with IGNORE_TIMING=1.
See issue #24.
=> Add check: hard error if Vivado timing fails.

common/src/main.c
=> Enable clean exit from simulation ('x' from top menu).

docs/source/docs/index.rst, docs/source/docs/md_example.md
=> Restore md_example.md.

docs/source/index.rst, docs/source/setup-guide.rst, docs/source/step-by-step.rst, docs/source/vivado-install.rst
Further docs on the setup and installation process. Largely copied
from my notes. May contain errors and ommissions.
=> docs: add setup and installation

docs/source/index.rst, docs/source/projects/mnv2_first.rst
Add documentation about mnv2_first.
=> docs: add mnv2_first.rst

proj/proj.mk, soc/nexys_video.mk, soc/nexys_video.py
NB: You must use a slower-than-default UART_SPEED since the Nexys video board uses a FT232RL for UART.
=> Add 'PLATFORM=nexys_video' support (prog, load, etc)

docs/source/projects/z_customizing_vex.rst
=> Add doc section on rebuilding VexRiscv.

.gitmodules, common/_hps/ld/linker.ld, common/src/benchmarks.c, common/src/perf.h, common/src/tflite.cpp, common/src/tflite.h, docs/source/_static/stylesheets/cfu-playground.css, docs/source/crash-course/gateware.rst, proj/mnv2_first/Makefile, proj/proj.mk, proj/proj_template_v/Makefile, scripts/hps_prog, scripts/xxd.py, soc/hps-notes, soc/hps.mk, soc/hps_platform.py, soc/hps_soc.py, soc/patch.py
Add support for internal board.
=> Internal board

.gitmodules
=> Add litespi submodule.

common/src/benchmarks.c, soc/arty.py
=> Add Arty spiflash option; add benchmarks when flash is present.

proj/mnv2_first/Makefile, proj/mnv2_first/renode/hps.repl, proj/mnv2_first/renode/hps.resc
=> Enable SW-only build for CI; add Renode files.

common/interact.expect, scripts/scanprof.py
* remove "--no-crc" from expects script
* fix scanprof.py regex for new profiler output
=> Fix some stuff that hadn't been tested in a while.

scripts/setup
This is required to build flashrom.
=> Add GCC dependency

proj/proj_template_v/src/proj_menu.c
=> Add simple table output of CFU for inputs 0..5 x 0..5.

soc/arty.mk
=> Update bitstream name arty.bit --> digilent_arty.bit.

docs/source/projects/zz_fccm_2021.rst
=> Add landing page for FCCM 2021 demo night.

.gitmodules
I have changed the 10000 constant to 10 in my fork.
=> Point to my litespi fork with cs timeout workaround.

.github/workflows-src/test-projects.yml, .github/workflows/check-doc-sw.yml, .github/workflows/test-projects.yml
This is to address #84 .
I'm not yet sure if we should have a filter for gh action yml changes, investigating.
=> Do not run workflows on unrelated path changes

proj/example_cfu_v/cfu.v, proj/proj.mk, soc/qmtech_wukong.mk, soc/qmtech_wukong.py
follow TCal-X, add rst signal into proj/example_cfu_v/cfu.v
=> add rst into proj/example_cfu_v/cfu.v

common/Makefile, proj/proj_template/src/proj_menu.c
change variable setting from signed to unsigned and for range in 
do_exercise_cfu_op0() of proj/proj_template/src/proj_menu.c
=> change variable setting and range in  do_exercise_cfu_op0()

common/Makefile, scripts/fix_cfu_dis.py
=> Disassembly: align lines; now have two versions w/, w/o source.

soc/sim.mk, soc/sim.py
=> Simplify sim build, don't use CPU wrapper.

.gitmodules, common/Makefile, common/src/perf.h
My Litex change is on top of a bump, so there are many unrelated changes there.
=> Add Fomu/cfu support (litex, pythondata_cpu_vexriscv).

.github/workflows/test-projects.yml
=> Update test-projects.yml (change in mithro/actions-includes)

common/src/playground_util/dump.cc, common/src/playground_util/dump.h, proj/tail_rom/Makefile, proj/tail_rom/src/calc_once_data.cc, proj/tail_rom/src/calc_once_data.h, proj/tail_rom/src/proj_tflite.cc, proj/tail_rom/src/tensorflow/lite/micro/kernels/conv_common.cc, proj/tail_rom/src/tensorflow/lite/micro/kernels/depthwise_conv_common.cc
With the merge of the tail rom 2 PR (#128), loading models can be quite irritating.
This PR allows models to run without outputing the ROMable content.
=> Tail rom 3

proj/proj.mk
=> Make sure TARGET is not passed to the TFLM make.

common/src/benchmarks.c, common/src/metrics.c, common/src/metrics.h, common/src/models/magic_wand/magic_wand.cc, common/src/models/micro_speech/micro_speech.cc, common/src/models/mlcommons_tiny_v01/anomd/anomd.cc, common/src/models/mlcommons_tiny_v01/imgc/imgc.cc, common/src/models/mlcommons_tiny_v01/kws/kws.cc, common/src/models/mlcommons_tiny_v01/vww/vww.cc, common/src/models/mnv2/mnv2.cc, common/src/models/pdti8/pdti8.cc, soc/board_specific_workflows/lattice_crosslink_nx_evn.py
This PR (WIP) introduces a way to measure the on-board SPI flash chip activity (e.g. % time when CS line is asserted).
=> Add CS line activity measurement

proj/hps_accel/Makefile, proj/hps_accel/cfu.py, proj/hps_accel/cfu_gen.py, proj/hps_accel/renode/litex-vexriscv-tflite.repl, proj/hps_accel/renode/litex-vexriscv-tflite.resc, proj/hps_accel/renode/litex-vexriscv-tflite.robot, proj/hps_accel/src/README.md, proj/hps_accel/src/proj_menu.c, proj/hps_accel/src/software_cfu.c, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv_accel.cc, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv_accel.h
This is just a starting point, no substantial acceleration is done yet.
=> add a new project for accelerating the HPS model

common/src/models/mnv2/mnv2.cc, common/src/tflite.cc
Several quality-of-life improvements for tflite.cc
=> tflite.cc improvements

.gitignore, docs/source/step-by-step.rst
"The Step-by-Step Guide to Building an ML Accelerator" section of our documentation was just marked as `TODO`. This PR fills in this section of our docs with an overview of:
- Making a project
- Profiling the software
- Doing simple software optimizations
- Creating a SIMD MAC instruction in the reader's choice of nMigen or Verilog
By the end of the tutorial, inference with the `pdti8` model is sped up from `183,087,673` cycles to `85,771,518` cycles.
I'd welcome suggestions for changes to the content or explanations!
=> Fill in the Step-by-Step Guide in our docs.

proj/hps_accel/src/blocks.cc, proj/hps_accel/src/blocks.h, proj/hps_accel/src/blocks_test.cc, proj/hps_accel/src/blocks_test.h, proj/hps_accel/src/proj_menu.c
Documents some building blocks for an initial accelerator architecture.
=> hps_accel/blocks.h: New header file.

proj/hps_accel/Makefile, proj/hps_accel/src/blocks.cc, proj/hps_accel/src/hps_cfu.h, proj/hps_accel/src/software_cfu_cc.cc
Adds a software version of CFU ops.
=> hps_accel: software accelerator

proj/hps_accel/gateware/stream.py, proj/hps_accel/gateware/test_stream.py
These are just the basics. It could be improved with a little typechecking, and won't be truly useful until we also have stream wrappers for FIFO and memories, and some of the utility classes of the kind LiteX provides, such as BinaryActor.
Would a appreciate any comments.
I have a further PR coming which will build on this.
=> New Stream API

docs/source/step-by-step.rst
PR #170 changed the API for nMigen CFUs. This PR updates the step-by-step.rst doc to match these changes.
=> Update step-by-step doc to match new nMigen cfu API.

proj/hps_accel/gateware/constants.py, proj/hps_accel/gateware/get.py, proj/hps_accel/gateware/hps_cfu.py, proj/hps_accel/gateware/set.py, proj/hps_accel/gateware/stream.py, proj/hps_accel/gateware/test_get.py, proj/hps_accel/gateware/test_hps_cfu.py, proj/hps_accel/gateware/test_set.py, proj/hps_accel/src/proj_menu.cc, proj/hps_accel/src/software_cfu.cc, proj/hps_accel/src/software_cfu.h
Adds a set instruction that is used to set configuration registers.
=> hps_accel/set: New set instruction

proj/hps_accel/gateware/get.py, proj/hps_accel/gateware/hps_cfu.py, proj/hps_accel/gateware/macc.py, proj/hps_accel/gateware/set.py, proj/hps_accel/gateware/test_hps_cfu.py, proj/hps_accel/gateware/test_macc.py, proj/hps_accel/src/blocks.cc, proj/hps_accel/src/hps_cfu.h
Adds a hardware implementation for multiply accumulate
=> hps_accel - adds macc hw implementation

proj/hps_accel/gateware/sp_mem.py, proj/hps_accel/gateware/stream.py, proj/hps_accel/gateware/test_get.py, proj/hps_accel/gateware/test_set.py, proj/hps_accel/gateware/test_sp_mem.py
I'm not completely happy with the implementation - it's too complex, so am continuing to work on refactoring.
Built on #194 (hw macc)
=> Single port memory

proj/hps_accel/gateware/constants.py, proj/hps_accel/gateware/get.py, proj/hps_accel/gateware/hps_cfu.py, proj/hps_accel/gateware/input_store.py, proj/hps_accel/gateware/set.py, proj/hps_accel/gateware/sp_mem.py, proj/hps_accel/gateware/stream/stream.py, proj/hps_accel/gateware/test_get.py, proj/hps_accel/gateware/test_hps_cfu.py, proj/hps_accel/gateware/test_input_store.py, proj/hps_accel/gateware/test_sp_mem.py, proj/hps_accel/src/blocks.cc
Better handling of src_loc_at for Sinks and Sources. This helps quite a
bit with interpreting vcd files.
=> hps_accel: input store

soc/hps_soc.py
It was fun while it lasted :monkey:
=> hps: remove monkey-patch for Oxide lack of I/O flip-flop

.gitignore, environment, proj/hps_accel/gateware/get.py, proj/hps_accel/gateware/hps_cfu.py, proj/hps_accel/gateware/set.py, proj/hps_accel/gateware/stream/actor.py, proj/hps_accel/gateware/test_hps_cfu.py, proj/mnv2_first/gateware/store.py, proj/mnv2_first/gateware/test_mnv2_cfu.py, proj/mnv2_first/gateware/test_store.py, scripts/setup
Removes several extraneous directories from PYTHONPATH, and adds support for vscode's .env file.
=> Tidying up Python library path handling

proj/hps_accel/gateware/constants.py, proj/hps_accel/gateware/hps_cfu.py, proj/hps_accel/gateware/set.py, proj/hps_accel/gateware/test_hps_cfu.py, proj/hps_accel/gateware/test_set.py, proj/hps_accel/src/blocks.cc, proj/hps_accel/src/blocks.h, proj/hps_accel/src/blocks_test.cc, proj/hps_accel/src/software_cfu.h, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv_accel.cc
This is my first attempt from last week, which uses an explicitly register write from the CPU to "turn the crank" on each iteration.
=> hps_accel: connect stores directly to macc

environment
=> Remove debug dump accidentally left in script.

proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv_accel.cc, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv_accel.h
Loads filters less often, for ~50% cycle saving.
More details of measurements here
https://gist.github.com/alanvgreen/53420020cfbe979ad6835eed75015254
=> hps_accel: load filters less often

common/src/perf.cc
Measures overhead of perf counters. The overhead is 11 cycles per
enable and disable pair. 3 cycles of this overhead is measured by
the counter.
Also adjusts the output of perf_print_all_counters() to account for the
three cycles of measured overhead.
=> common/perf.cc: Measure overhead

proj/hps_accel/gateware/mem.py, proj/hps_accel/gateware/test_mem.py
A simpler memory that is written one 32 bit word at a time and read 4
words (128bits) at a time.
=> hps_accel/mem: new WideReadMemory class

.gitmodules, proj/proj.mk, scripts/generate_renode_scripts.py
This removes the obsolete submodule and its uses.
=> Drop litex-renode submodule

.github/workflows/check-doc-sw.yml, .github/workflows/gateware.yml, .github/workflows/test-projects.yml, scripts/Dockerfile, scripts/setup
Right now wget is extremely noisy or completely silent (in Dockerfile).
It makes sense to have some output indicating the progress, but frankly
the default settings make CI logs unreadable.
This reduces the output so that each line covers 32M of downloaded data.
=> Unify and reduce wget output in the whole project

proj/hps_accel/Makefile
@tcal-x is there anything else I should test for the litedram bump, apart from that my designs are still working fine on Arty?
=> bump litedram and reduce hps_accel on Arty to 75MHz

scripts/parallel-nextpnr-nexus
=> In parallel pnr script, check if bash is supported version.

.github/workflows/fmax-trials-fresh-build.yml, .github/workflows/fmax-trials.yml, conf/environment.yml
=> Distinguish names of oxide fmax workflows; increase timeout.

.gitmodules, common/Makefile, common/src/stdio.c, conf/requirements.txt, proj/proj.mk, scripts/meson, scripts/setup
=> LiteX bump including picolibc.  

common/src/playground_util/print_params.cc, proj/hps_accel/Makefile, proj/hps_accel/gateware/constants.py, proj/hps_accel/gateware/get.py, proj/hps_accel/gateware/hps_cfu.py, proj/hps_accel/gateware/post_process.py, proj/hps_accel/gateware/stream/fifo.py, proj/hps_accel/gateware/stream/gearbox.py, proj/hps_accel/gateware/stream/test_gearbox.py, proj/hps_accel/gateware/test_hps_cfu.py, proj/hps_accel/src/blocks.h, proj/hps_accel/src/global_debug.cc, proj/hps_accel/src/global_debug.h, proj/hps_accel/src/software_cfu.cc, proj/hps_accel/src/software_cfu.h, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv_accel.cc
Sends output from the post process pipeline to a FIFO so it can be processed asynchronously.
=> hps_accel: new post process pipeline

soc/hps_soc.py
4 LRAMs are used for the arena, 1 LRAM for main memory.
The arena is created at 0x60000000.
Testing: 
* It built with the `hps_accel` CFU gateware and met timing (80MHz+).
* Exercised on the proto2 board using BIOS.
Software has *not* been altered to use the arena.
=> Add --separate-arena option to create tensor arena.

README.md, docs/source/setup-guide.rst, docs/source/vivado-install.rst
The diffs in the setup guide will be too confusing to make sense of, so just look at the generated RTD site.
=> README/docs update for other boards, new toolchains, Conda.

soc/board_specific_workflows/ice40up5k.py
=> Bump python deps to tip of main/master.

proj/hps_accel/gateware/gen2/accelerator.py, proj/hps_accel/gateware/gen2/filter.py, proj/hps_accel/gateware/gen2/post_process.py, proj/hps_accel/gateware/gen2/ram_input.py, proj/hps_accel/gateware/gen2/test_accelerator.py, proj/hps_accel/gateware/gen2/test_filter.py, proj/hps_accel/gateware/gen2/test_post_process.py, proj/hps_accel/gateware/gen2/test_ram_input.py
Adds input fetching logic to the accelerator core.
=> gen2: Add InputFetcher to AcceleratorCore

.github/workflows/fmax-trials-fresh-build.yml, .github/workflows/fmax-trials.yml, .github/workflows/fomu.yml, .github/workflows/oxide.yml, .github/workflows/symbiflow.yml
=> Give GHA jobs more meaningful names.

proj/hps_accel/Makefile, proj/hps_accel/cfu_gen.py, proj/hps_accel/gateware/gen1/constants.py, proj/hps_accel/gateware/gen2/accelerator.py, proj/hps_accel/gateware/gen2/constants.py, proj/hps_accel/gateware/gen2/filter.py, proj/hps_accel/gateware/gen2/hps_cfu.py, proj/hps_accel/gateware/gen2/test_accelerator.py, proj/hps_accel/gateware/gen2/test_hps_cfu.py, proj/hps_accel/src/blocks.cc, proj/hps_accel/src/blocks.h, proj/hps_accel/src/blocks_test.cc, proj/hps_accel/src/blocks_test.h, proj/hps_accel/src/conv2d_call.cc, proj/hps_accel/src/hps_cfu.h, proj/hps_accel/src/proj_menu.cc, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv_accel.cc, python/nmigen_cfu/cfu.py, python/nmigen_cfu/util.py
Integrates AcceleratorCore into a CFU with the mport extension.
=> hps_accel: CFU for gen2

.github/workflows/sync-renode.yml, .github/workflows/sync-tflm.yml
Spaces were not welcome by the rest of the scripting
=> Fix username for sync-* workflows

Makefile
=> Bump the SymbiFlow toolchain to latest versions

proj/hps_accel/Makefile, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/pad.h, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/pad_accel.cc, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/pad_accel.h
Accelerates the PAD operation for hps. This is a software-only change that reduces PAD times from 34M cycles to 3.3M cycles.
=> hps_accel/pad.h: Add unmodified pad.h

scripts/parallel-nextpnr-nexus
=> Fix parallel nextpnr script to detect failure in pipeline.

proj/hps_accel/Makefile, proj/hps_accel/gateware/gen2/constants.py, proj/hps_accel/gateware/gen2/hps_cfu.py, proj/hps_accel/gateware/gen2/test_hps_cfu.py, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/pooling.h, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/pooling_accel.cc, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/pooling_accel.h, python/nmigen_cfu/cfu.py
This PR reduces MAX_POOL execution time on the 09_20 model from 18M to 1.2M cycles.
=> hps_acell/pooling: Accelerate

.gitmodules, scripts/setup
=> Delete submodule third_party/flashrom.

conf/environment-symbiflow.yml, conf/environment.yml
=> conda: Add iceprog to environment.yml files

.github/workflows/supported_targets.txt, soc/hps_soc.py
=> Bump python dependencies (litex etc.).

scripts/parallel-nextpnr-nexus
ALSO: Make "router2" use explicit.  Add more timestamps.
=> Add latest best params to parallel pnr script.

scripts/parallel-nextpnr-nexus
Exit with an error code if place and route did not succeed.
=> scripts/parallel-nextpnr-nexus: error code

.github/workflows/sync-tflm.yml
This PR does not really resolve any problems we encountered, but cleans up the situation a bit
=> ci: tflm: Break the sync workflow early if tflm is not changed

scripts/install_oxide, scripts/setup
=> Add 'sudo apt update' to CI scripts

scripts/setup, soc/hps_proto2_platform.py
This PR enables the use of DSP register inference Yosys plugin by changing the synthesis script generated from Litex/Migen.
=> Use the DSP FF Yosys plugin for HPS

docs/source/overview.rst, docs/source/step-by-step.rst
=> Docs update: more boards; Verilog CFU handshake details.

docs/source/setup-guide.rst, proj/avg_pdti8/src/README.md, proj/example_cfu/src/README.md, proj/example_cfu_v/src/README.md, proj/hps_accel/src/README.md, proj/kws_micro_accel/DESIGN.md, proj/mnv2_first/src/README.md, proj/mport/src/README.md, proj/proj_accel_1/README.md, proj/proj_template/src/README.md, proj/proj_template_v/src/README.md, soc/vexriscv/README.md
- Trims trailing spaces from line ends in `.rst` and `.md` files.
- Clarified some instructions for digilent_arty
=> Documentation updates

scripts/install_oxide
=> Install dsp-ff plugin with 'install_oxide'.

scripts/install_oxide
=> Fix copy/paste error in install_oxide script.

proj/fccm_tutorial/Amaranth_for_CFUs.ipynb
Note book to support the FCCM '22 CFU-Playground tutorial.
=> fccm_tutorial/Amranth_for_CFUs.ipynb: new notebook

.github/workflows/fomu.yml, .github/workflows/oxide.yml, .github/workflows/symbiflow.yml, docs/requirements.txt, docs/source/conf.py, docs/source/index.rst, docs/source/interface.rst
Using a wavedrom plugin for sphinx!
=> readthedocs: Waveforms for many different CFU use cases.

scripts/scanprof.py
This version had been on the demo branch.
=> Update scanprof.py to parse prof (per-layer cycles) correctly.

scripts/setup
I added 4 dependencies I saw missing on a clean docker image.
Each commit is justified in the respective commit message
=> Add missing deps

common/interact.expect, proj/proj.mk
=> Add 'make PLATFORM=sim run' for gathering profiling data.

proj/hps_accel/gateware/gen2/post_process.py
Instead of patterns like 11, 111, 1111 for positive values and 100,
1000, 10000 for negative values, we use 100, 1000, 10000 for positive
values and 101, 1001, 10001 for negative values. The new bit patterns
are simpler to compute.
We then compensate for the increased threshold by using >= instead of >.
In hps-firmware, this reduces LUT usage from 8420 to 8373 (-47) and
increases fmax from 97.28 to 101.56.
Signed-off-by: David Lattimore <dml@google.com>
=> RoundingDivideByPowerOfTwo: Simplify threshold bit pattern

.github/workflows/symbiflow.yml, Makefile, conf/environment-symbiflow.yml, conf/requirements-symbiflow.txt
=> Update SymbiFlow/F4PGA installation, now works.

conf/requirements-symbiflow.txt
=> Pin f4pga zip file after discussion with @umarcor.

.github/workflows/verilate.yml
Currently expect this to fail.
=> Test for Verilator+conda (issue #568)

.github/workflows/hps.yml, common/_hps/hps/ld/linker.ld, proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h
=> CI test and fix for #658 (HPS software build).

third_party/tflite-micro/tensorflow/lite/micro/micro_profiler.cc
=> Patch tflite profiler until it's fixed upstream (#715).

.github/workflows/fomu.yml, .github/workflows/hps.yml, .github/workflows/oxide.yml, .github/workflows/symbiflow.yml, .github/workflows/test-projects.yml, .github/workflows/verilate.yml
=> Don't run build tests when just README.md is modified.

scripts/setup
Also add bus.h to downloaded files to fix #746
=> Use renode-verilator-library from a proper Renode SHA

.github/workflows/check-doc.yml, .github/workflows/fmax-trials.yml, .github/workflows/fomu.yml, .github/workflows/hps.yml, .github/workflows/oxide.yml, .github/workflows/run-pytests.yml, .github/workflows/symbiflow.yml, .github/workflows/test-projects.yml, .github/workflows/verilate.yml
Signed-off-by: tcal-x <tcal@google.com>
=> Bump workflow actions to v3 to get node16.

proj/donut-accel/README.md
Also add instructions for running in Verilator.
=> Add some results to donut README.
