.readthedocs.yml

Add .readthedocs.yml; don't load submodules.

---

.readthedocs.yml

Fix location of conf.py file for readthedocs.

---

.github/workflows/check-doc-sw.yml
README.md
common/interact.expect
proj/proj.mk

The interact.expects script is updated to handle either simulation or Arty board.
CI invokes "make PLATFORM=sim unit", which invokes the expect script, which spawns and interacts with "make PLATFORM=sim load", and then kills it.

Add Verilator simulation (tflm unit test) to CI.

---

python/nmigen_cfu/cfu.py

RR-format now uses {funct7,funct3} (10b) as function_id.
REQUIRES SUBMODULE UPDATE.

CFU instr encoding: conform to CFU spec.  Add I-format.

---

scripts/setup

This adds `make` as one of the requirements. Does not change much for a regular user, but helps in the CI scenario

Add make as a requirement

---

soc/hps_soc.py

This PR adds an option to use liteSPI QSPI controller with the HPS platform. It requires a fix from https://github.com/enjoy-digital/litex/pull/891 to work.
Also, I had to change CSR bus width to 32 (liteSPI defines such registers). This can potentially be changed in litespi (if 8 bit CSR bus is a must here).
Signed-off-by: Karol Gugala <kgugala@antmicro.com>

hps_soc: add option to use litespi

---

proj/proj_template_v/renode/hps.repl
proj/proj_template_v/renode/hps.resc
soc/hps.mk

* Add "USE_LSE=1" and "USE_YOSYS=1" options for gateware build
- these still use Radiant place and route
* Add Renode platform and script files for HPS
- only in proj_template_v; I need to centralized these...

HPS updates: allow alt synth tool; Renode files.

---

scripts/setup

This change prints the URL of the GCC compiler installation
documentation when GCC is not found, or is an unrecognized version.
Currently, setup attempts to install GCC if one is not found. That is
almost always the wrong thing to do.
Fixes #57

scripts/setup: Improve gcc versioning

---

common/Makefile
scripts/fix_cfu_dis.py

Used to look like:
```
40003bfc:       2efe8e8b                0x2efe8e8b
```
Now looks like:
```
40003bfc:       2efe8e8b                cfu[23,0]  t4, t4, a5
```

Fix disassembly for CFU instructions in software.elf.dis.

---

.github/includes/actions/run-in-renode/action.yml
.github/workflows-src/Makefile
.github/workflows-src/requirements.txt
.github/workflows-src/run-in-renode.yml
.github/workflows-src/test-projects.yml
.github/workflows/run-in-renode.yml
.github/workflows/test-projects.yml
.gitignore
proj/mnv2_first/renode/hps.resc
proj/mnv2_first/renode/hps.robot
proj/mnv2_first/renode/litex-vexriscv-tflite.robot

This PR adds tests for both HPS and LiteX for mnv2_first project.
These tests will, eventually, be quite similar for all platforms. Right now they differ in one test case.
I would suggest keeping them separate for now and try to unify when we have more actual cases.
GitHub Actions workflow, on the other hand, is something that should be definitely unified.
I took the liberty of using @mithro 's actions-includes. This really solves all the issues with code reuse - otherwise each job is mostly copy-paste.
It does, however, require some additional consideration:
1. I used the `.github/workflows-src/Makefile` from SymbiFlow/fasm. It has, obviously, `SymbiFlow Authors` copyrights. Is this an issue?
2. The `.github/workflows/test-projects.yml` is autogenerated. It requires running `make update` …

mnv2_first tests

---

soc/hps_soc.py

Default is Synplify.
Specify 'yosys' to get Yosys,
or 'lse' to get (Radiant) LSE.

Pass --synth-mode option to Radiant tools (lse, yosys).

---

proj/example_cfu_v/cfu.v
proj/proj_template_v/cfu.v
python/nmigen_cfu/cfu.py
soc/arty.mk
soc/arty.py
soc/cfu/Cfu.v
soc/hps.mk
soc/hps_soc.py
soc/nexys_video.mk
soc/nexys_video.py
soc/qmtech_wukong.mk
soc/qmtech_wukong.py

Continuation of PR #101.
Updated VexRiscv verilogs to remove wrappers and not rename the VexRiscv core with "_inner".
Small updates to the handling of Slim VexRiscv -- they can still use the new CFU integration,
their source just needs to be changed.

Simplify top scripts (continuation of PR #101)

---

scripts/Dockerfile

I'm not really sure if this should be merged. I created this Dockerfile and I use it for my development. Maybe someone will find it useful.
But I'm ok with rejecting this PR if you don't see it fitting in this repo.
Build the dockerfile with `cd scripts; docker build -t cfu-playground .`
Run with `docker run -ti cfu-playground`

Add a simple Dockerfile with all dependencies

---

python/nmigen_cfu/cfu.py

This is a suboptimal fix because the generated Verilog Cfu module will have both "rst" and "reset" ports.   This PR ties them together, so that even though only "reset" is driven by sys_rst, it gets passed to the "rst" net inside the Cfu.

In nMigen Cfu, tie implicit "rst" to explicit "reset".

---

soc/hps_platform.py

On the CrossLink-NX, the internal oscillator nominally runs at 450MHz but may
actually run at 405-495MHz. On my board it appears to run at ~488MHz.
If the oscillator produces a clock signal faster than we are expecting, it
means we actually have less time for signals to propagate. We need to specify a
period constraint accounting for the worst case (10% faster than nominal)
otherwise there is a chance that the design will meet timing, but when run on a
real device signals will not propagate fast enough resulting in strange
misbehaviour.

hps: make period constraint account for imprecise internal oscillator

---

environment
proj/proj.mk
proj/proj_template/Makefile
proj/proj_template_v/Makefile
soc/board_specific_workflows/__init__.py
soc/board_specific_workflows/digilent_arty.py
soc/board_specific_workflows/general.py
soc/board_specific_workflows/run_unit_tests.sh
soc/board_specific_workflows/test_digilent_arty.py
soc/board_specific_workflows/test_general.py
soc/board_specific_workflows/workflow_args.py
soc/common_soc.py

This PR aims to make the CFU-Playground easier to operate with different FPGA boards.
- The `proj.mk` file checks for both a `/dev/ttyUSB` and `/dev/ttyACM` device.
- The default models included in the template are reduced back to just `pdti8`instead of the entire TFLM examples (for size and consistency reasons).
- The `common_soc.py` file has had its logic moved to a class that can be easily subclassed to provide board-specific tweaks if they need to exist. It has also been formatted to conform with the PEP 8 style guide.

Make CFU-Playground more board agnostic, easier to extend for specific boards.

---

soc/hps_soc.py

The --nextpnr-timingstrict and --nextpnr-seed options are of particular
interest.

hps: also expose command line options for the Oxide toolchain

---

common/src/tflite.cpp

Previously, our code used one of two constants for either a bigger or smaller tensor arena. This worked well, but  it poses a problem when RAM is limited and the arena size is larger than necessary (for example, when fitting the CFU-Playground on a small board like the Fomu or iCEbreaker). This PR replaces the previous approach with a compile-time determination of the smallest possible tensor arena depending on the models included in the build.

Determine smallest possible tensor arena at compile time.

---

.gitmodules
soc/board_specific_workflows/digilent_arty.py

We get one SymbiFlow fix (force the make to be non-parallel)
with the LiteX bump.  
edit: see https://github.com/enjoy-digital/litex/pull/945
Another fix is to disable jtagbone on Arty
(it uses a bel not yet handled by SymbiFlow).
As a side effect, we get a bunch of fixes on LiteX and liteSPI.

Fix two SymbiFlow issues; bump Litex/litedram/litespi.

---

common/src/playground_util/dump.cc
common/src/playground_util/dump.h
proj/tail_rom/src/calc_once_data.cc
proj/tail_rom/src/calc_once_data.h
proj/tail_rom/src/proj_tflite.cc
proj/tail_rom/src/tensorflow/lite/micro/kernels/conv_common.cc
proj/tail_rom/src/tensorflow/lite/micro/kernels/depthwise_conv_common.cc

Second set of changes addressing tail memory. To land after #125.
This functionality dumps the calculated data. Future changes will compile this calculated data into the program.

Tail rom 2

---

soc/hps_soc.py

The motivation here is to have an easier way to debug and measure SPI flash performance (while the CPU is not executing directly from SPI flash).
This PR introduces the support only, but does not enable it. I am testing it with some local hacks like this:
```diff
diff --git a/common/src/main.c b/common/src/main.c
index 759bb22..fb1acea 100644
--- a/common/src/main.c
+++ b/common/src/main.c
@@ -47,7 +47,7 @@ static struct Menu MENU = {
MENU_ITEM('2', "Functional CFU Tests", do_functional_cfu_tests),
MENU_ITEM('3', "Project menu", do_proj_menu),
MENU_ITEM('4', "Performance Counter Tests", perf_test_menu),
-        MENU_ITEM('5', "TFLite Unit Tests", tflite_do_tests),
+        //MENU_ITEM('5', "TFLite Unit Tests", tflite_do_tests),
MENU_ITEM('6', "Benchmarks", do_benchmarks_menu), …
```

hps: support for executing from LRAM

---

common/_common_soc/1bitsquared_icebreaker/ld/linker.ld

Previously the linker script for the iCEbreaker board:
- exposed unused symbols
- linked multiple empty input sections
- tried to load the `.bss` segment into spiflash
- had a subtle (but consequential) bug with the linking of the `.data` segment.
The bug with the linking of the `.data` segment allowed static variables to be placed in memory at `0x0`. A valid pointer to this static variable would then be mistaken as a null pointer (because it points to `0x0`), leading to incorrect program behavior. This was the cause of TFLM unit tests failing when no model was included in the binary (#133); the `tflite::testing::kInputShape` static array that is used in many of the convolution unit tests was mistaken as being a null pointer.
This PR fixes all of these issue in the linker script for the …

Fix and clean up linker script for iCEbreaker.

---

common/src/main.c
common/src/spiflash.c
common/src/spiflash.h

Just a couple of extra menu commands I am using to satisfy my paranoia that we are not reading garbage values from SPI flash, as we work on the faster speeds.
I put them into a new top-level menu since they aren't really benchmarks. Let me know if you would rather have them arranged differently.

add menu items for SPI flash debugging

---

docs/source/setup-guide.rst

1) Add info for installing renode
2) fix non working autolink for installing vivado
3) add python virtualenv info
4) add required nmigen
5) better instructions on how to activate the code after make load

Fix setup guide with missing steps and more info

---

soc/hps.mk

When Litex invokes Radiant, it always checks that timing was met.
When Litex invokes Oxide, by default it ignores timing checks but can be
told to enforce them with --nextpnr-timingstrict.
Fixes #58, at least for HPS.

hps: let Litex handle timing checks

---

docs/source/setup-guide.rst

* Make capitalization more consistent 
* `virtualenv` is not installed by default on Ubuntu 20, so include instructions
* Clarify litex_term exit instructions (double Ctrl-C)

Capitalization; install virtualenv if necessary; lxterm exit.

---

.gitmodules
common/src/benchmarks.c
common/src/metrics.c
common/src/metrics.h
common/src/models/magic_wand/magic_wand.c
common/src/models/micro_speech/micro_speech.c
common/src/models/mlcommons_tiny_v01/anomd/anomd.c
common/src/models/mlcommons_tiny_v01/imgc/imgc.c
common/src/models/mlcommons_tiny_v01/kws/kws.c
common/src/models/mlcommons_tiny_v01/vww/vww.c
common/src/models/mnv2/mnv2.c
common/src/models/pdti8/pdti8.cc
proj/avg_pdti8/renode/litex-vexriscv-tflite.repl
proj/example_cfu/renode/litex-vexriscv-tflite.repl
proj/example_cfu_v/renode/litex-vexriscv-tflite.repl
proj/mnv2_first/renode/hps.repl
proj/mnv2_first/renode/litex-vexriscv-tflite.repl
proj/proj_accel_1/renode/litex-vexriscv-tflite.repl
proj/proj_template/renode/litex-vexriscv-tflite.repl
proj/proj_template_v/renode/hps.repl
proj/proj_template_v/renode/litex-vexriscv-tflite.repl

This PR introduces displaying of additional dcache-related matrics from CPU's CSRs in benchmarks:
```
Running sequential stores benchmark
Hello, Store!
Val:28  Cycles: 11389084   Cycles/store: 10
[Dcache accesses] Before: 3223075888, After: 3224127310, Diff: 1051422
[Dcache refills]  Before: 952539, After: 952545, Diff: 6
[Dcache stalls]   Before: 89447457, After: 96635863, Diff: 7188406
```

Use dcache metrics CSRs in benchmarks

---

proj/proj.mk
scripts/Dockerfile
scripts/setup

This is a solution for #4.
`scripts/setup` will download and extract Renode portable to `third_party/renode`. Each time the script is called it checks if Renode exists and checks its version so it will download Renode or throw a warning about wrong version.
All calls of Renode in scripts will now use `third_party/renode/renode` to avoid problems with different versions or with lack of Renode itself.

Automate installing Renode

---

common/_common_soc/lattice_crosslink_nx_evn/ld/linker.ld
common/src/benchmarks.c
soc/board_specific_workflows/__init__.py
soc/board_specific_workflows/lattice_crosslink_nx_evn.py

Currently it is not possible to run benchmarks (or any other piece of software) from this repository on CNX EVN board. This PR adds a new platform (based on existing `hps` platform), that enables that by using the on-board SPI flash chip.
Building gateware/software (in project directory, e.g. `proj/proj_template`):
```
UART_SPEED=115200 PLATFORM=cnx_evn TARGET=lattice_crosslink_nx_evn make bitstream software
```
Flashing/uploading using `ecpprog` (in project directory, e.g. `proj/proj_template`):
```
ecpprog -so 2097152 build/software.bin
ecpprog -S ../../soc/build/cnx_evn.proj_template/gateware/cnx_evn_platform.bit
```

Enable running benchmarks on CrossLink NX Evaluation board

---

common/src/tflite.cc

Boards using tiny versions of VexRiscv (like ice40up5k derived boards) don't have the ability to write to the `mcycle` csr. This means incorrect cycle counts are printed in `tflite.cc` because `perf_set_mcycle(0);` is a no-op for these boards. This PR adds support for boards that can't write to `mcycle` by not calling `perf_set_mcycle` in `tflite.cc`.

Support boards without mcycle write support in tflite.cc

---

.gitignore

Currently `scripts/setup` installs Renode in `third_party/renode`. Git doesn't ignore this directory however. This PR adds `third_party/renode` to our `.gitignore` so that it doesn't show up in "Untracked files:"

Add third_party/renode to .gitignore.

---

proj/example_cfu_v/cfu.v
proj/proj_template_v/cfu.v

In `proj/proj_template_v` and `proj/example_cfu_v`, an older CFU module signature was used where `cmd_payload_function_id` was only 3 bits wide. The Verilog works fine from a functional standpoint, but as example projects it's probably best to extend the bit width to 10 bits so both funct7 and funct3 are visible.

Update bit widths of the `cmd_payload_function_id` port in Verilog CFUs.

---

proj/mnv2_first/renode/hps.repl
soc/hps_soc.py

Just a copy-paste of PR #149 for HPS. Like the other performance metrics changes this is going to the `hps-faster-flash` branch only.

hps: add SPI flash activity counter

---

common/src/tensorflow/lite/micro/micro_time.cc

In tflite-micro the profiling code uses int32_t to represent ticks,
presumably because it was intended to be fed from a relatively low
precision timer source and not the raw system clock cycle counter.
The HPS model (unaccelerated) has one layer which takes more than 2**31
cycles and so it was being displayed in the profile as taking negative
time.
Report "ticks" as clock cycles / 1024, instead of raw cycles. The choice
of divisor is arbitrary but 1024 can be implemented in a single shift
instruction and still makes the numbers easy to interpret (humans just
have to think of it as "kilocycles").
Also, for completeness sake, use the full 64-bit cycle counter in the
unlikely event that a single profiling event takes more than 2**32
cycles. This implementation of get_mcycle() is taken from …

report "ticks" to the tflite-micro profiler as cycles / 1024

---

docs/source/step-by-step.rst

PR #165 changed how we report "ticks" to the tflite-micro profiler
(cycles / 1024, instead of the raw cycle count). Update the example
output to match.

update profiler output in step-by-step accelerator guide to account for ticks = cycles / 1024

---

common/_common_soc/kosagi_fomu/ld/linker.ld
proj/proj.mk
soc/board_specific_workflows/__init__.py
soc/board_specific_workflows/kosagi_fomu.py
soc/board_specific_workflows/test_kosagi_fomu.py

This PR adds an explicit workflow for the Fomu board.
The majority of this process is similar to PR #129 which adds an explicit workflow to the iCEbreaker, the main differences being the bios isn't loaded on the Fomu and the Fomu requires a `TTY=` flag to be set on the command line.

Add Workflow for the Fomu.

---

proj/avg_pdti8/cfu.py
proj/avg_pdti8/util.py
proj/example_cfu/cfu.py
proj/hps_accel/cfu.py
proj/mnv2_first/gateware/mnv2_cfu.py
proj/proj_accel_1/cfu.py
proj/proj_template/cfu.py
proj/tail_rom/cfu.py
python/nmigen_cfu/cfu.py
python/nmigen_cfu/test_cfu.py

Brings API into line with other nmigen code by discouraging passing of modules between components.
A simple API for making CFUs with independent instructions is preserved via the simple_cfu() function, but CFUs with interdependent instructions should use a subclass of the CFU class, and instantiate their instructions in the elab_instructions() method. avg_pdti8/cfu.py has an example of a Cfu subclass.

Update Python CFU interface

---

common/src/tflite.cc

Removes commented-out OpResolver code. Since we are committed to using
the AllOpResolver, we do not need to add individual ops.

tflite.cc: Remove unused code

---

soc/board_specific_workflows/kosagi_fomu.py
soc/board_specific_workflows/test_kosagi_fomu.py

This PR bumps LiteX-Boards and our VexRiscv CPU to better support boards with constrained resources. Notably this allows the CFU-Playground to fit on the Fomu.
LiteX-Boards bump:
- Turn off LedChaser submodule in the Fomu workflow: https://github.com/litex-hub/litex-boards/pull/236 
VexRiscv bump:
- Minimize LC usage while increasing performance on the `fomu+cfu` variant by removing hardware division, memory/writeback stages, and adding a small icache: https://github.com/tcal-x/pythondata-cpu-vexriscv/pull/1

Bump LiteX-Boards and VexRiscv to minimize LC usage on Fomu.

---

soc/common_soc.py

This PR changes the error message displayed in `soc/common_soc.py` when we cannot find the target board in LiteX-Boards. The error message now lists out all of the supported boards so it's easier for a user to correct their mistake.

Improve error when we can't find target board in LiteX-Boards

---

proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h
proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv_accel.cc

@alanvgreen do you think it's okay to limit this to padding=valid for now and ignore padding=same? I see there was a discussion where we settled on padding=valid as a temporary solution, but I guess we will need padding=same support sooner or later?
Also worth noting that this causes the model evaluation to fail because the CFU ops are not fully implemented. If you switch it to software CFU implementation (not turned on by default currently) the golden tests pass but this is a severe speed regression. Should we fix that before merging this PR?

hps_accel: use accelerated multiply_accumulate() in convolution

---

proj/kws_micro_accel/Makefile
proj/kws_micro_accel/cfu.py
proj/kws_micro_accel/cfu_gen.py
proj/kws_micro_accel/src/proj_menu.c
proj/kws_micro_accel/src/software_cfu.c
proj/kws_micro_accel/src/software_cfu_cc.cc
proj/kws_micro_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h
proj/kws_micro_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/depthwise_conv.h
proj/kws_micro_accel/src/tensorflow/lite/micro/kernels/conv.cc
proj/kws_micro_accel/src/tensorflow/lite/micro/kernels/depthwise_conv.cc

This PR adds an empty project in `proj/kws_micro_accel` that I'll be using in the upcoming weeks. There's nothing in the project but the skeleton and a copy of the important TFLM ops.

Add skeleton project for keyword spotting acceleration.

---

.github/includes/actions/run-in-renode/action.yml
.github/workflows/test-projects.yml
proj/proj.mk

This fixes #175.
The `renode-scripts` recipe always requires `csr.csv`, so its prerequisite is now `$(SOFTWARE_ELF)` and we can assume that `csr.csv` will be present after a successful prerequisite run.

Fix `make renode` recipe

---

proj/avg_pdti8/Makefile

Note that no software CFU exists for pdti8, so it should not be expected
to work.
This is a fix for #174.

avg_pdti8/Makefile: note about software cfu

---

environment
scripts/install_oxide
soc/common_soc.mk
soc/hps.mk

Usage:
```
./scripts/install_oxide           # initial install
./scripts/install_oxide update    # pull any changes and rebuild and reinstall
```
Initial installation takes about 10 minutes on my gLinux laptop.
The three required repositories are cloned, not added as submodules, under third_party/.
All generated executables are also located under third_party, installed under third_party/usr/local/bin/.  The `environment` script has been updated to use them.
Once the installation is done, you can use them as follows:
```
make PLATFORM=hps USE_OXIDE=1 prog    # use full yosys/nextpnr-nexus flow
make PLATFORM=hps USE_YOSYS=1 prog    # use yosys + radiant pnr
```

Add script to do local install of PrjOxide toolchain.

---

common/Makefile
common/src/fb_util.c
common/src/models/mnv2/mnv2.cc
common/src/models/pdti8/pdti8.cc

Hi, 
after some try and error, to solve cache content not sync with main memory. there two parts have to modified. 
1. according to https://github.com/litex-hub/linux-on-litex-vexriscv/issues/228
the l2_cache_reverse has to be added in litex_boards/target/xxx_board.py in self.add_sdram() function setting.
2. add flush_cpu_dcache(), flush_l2_cache() after framebuffer function execution. 
the fb_util.c is been added two flush functions.
BR, Akio

add flush_cpu_dcache(), flush_l2_cache() to sync cache content

---

docs/source/index.rst

This PR adds a definition for CFU to `index.rst` in our docs so new readers don't need to guess what it means. The extra whitespace is added as a `.rst` formatting quirk to allow nested unordered lists without making the previous list element bold.
The new modified section is shown below:
Resolves #201

Add CFU definition to `index.rst`.

---

proj/proj.mk
soc/common_soc.mk
soc/hps.mk
soc/sim.mk

This PR adds explicit support for `cfu.sv` files in our build system.
I tested this with projects in `proj/` and my own SystemVerilog CFU.

Add Makefile support for SystemVerilog CFUs.

---

soc/board_specific_workflows/kosagi_fomu.py
soc/board_specific_workflows/test_kosagi_fomu.py

This PR removes the `timer0` CSRs and related functionality from the LiteX build in the Fomu workflow. The timer is not required for the CFU-Playground, but is necessary for compiling the bios. Thus, the removal of the timer also necessitates the removal of the LiteX bios; this isn't a problem because we didn't use the LiteX bios in the first place with the Fomu.
Overall this change saves us ≈328 LCs which can be utilized in more important applications (like a larger CFU).

Remove timer from the LiteX build in Fomu workflow.

---

soc/board_specific_workflows/digilent_arty.py
soc/board_specific_workflows/test_digilent_arty.py
soc/common_soc.mk

This PR adds an `EXTRA_LITEX_ARGS` command line argument to our build system. These extra arguments can be parsed in board-specific workflows to allow for a more flexible building process; ie. `make prog EXTRA_LITEX_ARGS="--variant a7-100"`.
The Arty workflow has been modified to use these extra args to specify the variant of the Arty board (`a7-35` or `a7-100`).

Add ability to pass extra arguments into board-specific workflows.

---

common/src/perf.cc
common/src/perf.h
common/src/tensorflow/lite/micro/micro_time.cc
common/src/tflite.cc

Moves the 64 bit get_mcycle() instruction from micro_time.cc to perf.h
so that it is accessible in other contexts. In particular, use it to
print a more accurate time for long running model evaluations.

common: add perf_get_mcycle64 function

---

.gitignore
scripts/install_oxide

Adds some prerequisites for the building of yosys, nextpnr and project
oxide. These were found by building on a relatively fresh Debian-based
image. Others attempting the install may find further prerequisites in
future.

scripts/install_oxide: Add some prerequisites

---

soc/hps_proto0_platform.py

These pins are in bank 0 which means they can only do LVCMOS18 not
LVCMOS18H. The IO standard was already correctly declared on the
'spiflash' resource, it was just incorrect on 'spiflash4x' (currently
unused).
The proto2 platform definition is already correct, I checked it when
I added it.

hps: fix IO standard for spiflash4x resource on proto0

---

soc/board_specific_workflows/kosagi_fomu.py
soc/board_specific_workflows/test_kosagi_fomu.py

This PR increases the performance of the Fomu VexRiscv build (adds single-cycle multiply, single-cycle shift, and more icache) and removes the `ctrl` registers (registers for resetting the SoC/CPU) from the Fomu LiteX build. Overall this nets us an extra ≈110 LCs for use in a CFU, while making the VexRiscv build significantly more effective (see https://github.com/tcal-x/pythondata-cpu-vexriscv/pull/3 for more on why the changes were made).
This PR also bumps LiteSPI, where some changes have been made to decrease resource utilization.

Modify Fomu workflow and VexRiscv build to save LCs and gain performance.

---

scripts/install_oxide

Without this compilation will complain that clang is missing when building yosys:
```
BUILDING YOSYS
/bin/sh: line 1: clang: command not found
```

script/install_oxide: add missing clang dep

---

proj/kws_micro_accel/cfu.sv
proj/kws_micro_accel/mac.sv
proj/kws_micro_accel/rcdbpot.sv
proj/kws_micro_accel/rdh.sv
proj/kws_micro_accel/src/kws_cfu.h
proj/kws_micro_accel/src/proj_menu.cc
proj/kws_micro_accel/src/software_cfu.cc

With the new resources afforded to the Fomu build (see #215 and #223) the kws_micro_accel CFU has been updated with new features.
- It continues to perform (optionally SIMD) multiply-and-accumulate operations but now with a status bit that controls the `InputOffset` value. This allows the CFU to be used during the first layer of convolution (which requires the different offset).
- The post-processing section of convolution and depthwise convolution has been moved mostly into the CFU with the newly added "rounding clamping divide by power of two" and "rounding doubling high 32 bit" operations.
- We don't have enough DSP tiles in the FPGA to move the entirety of the post-processing into gateware so we utilize the updated single-cycle multiply in our CPU before passing our inputs to the CFU. …

Update gateware/software CFU and tests in kws_micro_accel.

---

proj/kws_micro_accel/Makefile
proj/kws_micro_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv.h
proj/kws_micro_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/depthwise_conv.h
proj/kws_micro_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/kws_conv.h
proj/kws_micro_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/kws_depthwise_conv.h
proj/kws_micro_accel/src/tensorflow/lite/micro/kernels/conv.cc
proj/kws_micro_accel/src/tensorflow/lite/micro/kernels/depthwise_conv.cc

PR #224 introduced new functionality to the `kws_micro_accel` CFU. This PR utilizes these new CFU instructions in optimized `CONV2D` and `DEPTHWISE_CONV2D` kernels.
This decreases the cycles per inference to around 25 million, which, compared to the very initial starting point (before any optimizations) of 1.89 billion cycles, is a bit over a cumulative 75x speedup. Golden tests, TFLM unit tests, and the CFU tests all pass with these new changes.

Use the `kws_micro_accel` CFU in software and optimize software ops.

---

.gitmodules
common/_common_soc/lattice_crosslink_nx_evn/ld/linker.ld
soc/board_specific_workflows/lattice_crosslink_nx_evn.py

This PR enables the usage of QPI mode on CNX ENV board. It depends on the changes made in litex-hub/litespi#53 and in enjoy-digital/litex#979. Since we're switching to the flashboot process that LiteX provides, the additional step of using the MiSoC image file writer (`mkmscimg`) is required before flashing the software to insert length and CRC32:
```
python <path_to_litex>/litex/soc/software/mkmscimg.py -o output.bin --little --fbi <path_to_cfu_proj>/build/software.bin
```
PS I've noticed that this repo is not using the upstream version of LiteX and instead is using the fork that @tcal-x provides. What is the reason behind this and are there plans to upstream these changes?

Enable QPI mode for Crosslink-NX Evaluation board

---

.gitmodules
soc/board_specific_workflows/ice40up5k.py

In order to make maintenance easier until the Fomu CPU variant is upstreamed, this PR switches off of @tcal-x's LiteX fork and monkey-patches the Fomu variant into the official LiteX at runtime. This patch should be removed once changes have been upstreamed. 🐒

Use upstream LiteX with local monkey-patch for CPU variant.

---

proj/hps_accel/gateware/test_hps_cfu.py

Turns off VCD file generation - this should not have been checked in.

hps_accel/test_hps_cfu: turn off vcd file

---

proj/hps_accel/Makefile
proj/hps_accel/gateware/constants.py
proj/hps_accel/gateware/filter_store.py
proj/hps_accel/gateware/get.py
proj/hps_accel/gateware/hps_cfu.py
proj/hps_accel/gateware/input_store.py
proj/hps_accel/gateware/set.py
proj/hps_accel/gateware/test_filter_store.py
proj/hps_accel/gateware/test_hps_cfu.py
proj/hps_accel/src/blocks.cc
proj/hps_accel/src/blocks.h
proj/hps_accel/src/hps_cfu.h
proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv_accel.cc

This is largely a copy-paste from the input store implementation, with constants and memory depth tweaked, as a starting point. We expect the two implementations will start to diverge after this (particularly since the filter store will need to be shrunk to fit inside the fewer EBRAMs on HPS).
The tests in test_filter_store.py are independently implemented, which is why they look quite different to test_input_store.py.
This includes two x'ed out test cases which cover some edge cases around reset behaviour, which I think *should* work, but currently don't. It's probably not too important because we can easily avoid the problematic sequence of operations by just making sure we don't ever do that in software.

hps_accel: implement filter store registers

---

proj/hps_accel/gateware/constants.py
proj/hps_accel/src/tensorflow/lite/kernels/internal/reference/integer_ops/conv_accel.cc

The first 18 convolution layers of the HPS model can still load all
their filter values in one go, outside the loop. The final 9 larger
layers will instead need to load the filter in batches inside the loop,
to fit within the 2048-word capacity.
This gets the filter store down to consuming 4 EBRAMs on HPS.

hps_accel: shrink filter store to 2048 words

---

common/src/perf.cc
common/src/perf.h

Now acessing perf CSRs is controlled by a LiteX-defined
flag CONFIG_CPU_PERF_CSRS instead of NPROFILE.
This makes it safe to enable profiling on CPU variants
without perf CSRs (such as fomu and slim).

Separate perf CSRs from NPROFILE flag.

---

proj/hps_accel/Makefile
soc/board_specific_workflows/general.py
soc/board_specific_workflows/workflow_args.py

Vivado has been unable to make timing for `proj/hps_accel` on the `main` branch since commit c55db9a9, but we didn't notice due to #254. Reducing the clock to 80MHz gets it passing again.

hps_accel: reduce clock on Arty to 80MHz

---

proj/proj.mk

Fixes #260.    There was a copy in the make recipe from the old way of doing things,
and it would cause an error when there was not already a ./renode directory.

Fix #260, remove unnecessary copy of software.elf to ./renode/.

---

common/interact.expect
proj/proj.mk

This adds 3 targets:
- renode-headless, which just runs Renode in a single console
- unit-renode, same as `make unit` but running in Renode
- run-renode, similar to `make run`, added for completeness
All of these accept the `TARGET` variable to select the actual target.
Closes #271

Renode expect support

---

proj/hps_accel/Makefile
proj/mnv2_first/Makefile
soc/board_specific_workflows/general.py
soc/board_specific_workflows/ice40up5k.py
soc/board_specific_workflows/workflow_args.py
soc/common_soc.py
soc/hps.mk
soc/hps_soc.py
soc/patch_cpu_variant.py

Now there is monkey patching both at the general level, plus more
that is ice40-specific.
In both cases, when updating core.VexRiscv.add_soc_components, 
call the previous version rather than completely replacing it.

Monkey patching for CPU variants incl. slim, perf.

---

environment
scripts/parallel-nextpnr-nexus
soc/hps_proto2_platform.py

Enable builds of hps_accel using oxide toolchain
Reduces clock divisor
Runs many nextpnr-nexus in parallel
Tested with
```
cd proj/hps_accel
time make PLATFORM=hps bitstream
```
For me this runs 54 separate copies of nextpnr and terminates in 14 minutes:
```
make[1]: Leaving directory '/usr/local/google/home/avg/src/CFU-Playground/soc'
real    14m17.820s
user    778m42.951s
sys     1m17.644s
```

Enable builds of hps_accel using oxide toolchain

---

common/Makefile

software.elf.sym was being generated with -s, which caused the entire
content of the elf file to be translated into hex. This fix uses -t
instead which just includes symbol positions and lengths.

common/Makefile: fix software.elf.sym

---

common/Makefile

The software.elf.dis and software.elf.dis_with_source disassembler dumps
refer to a lot of C++ symbols from TFLM. The dump is easier to read if
we pass it through c++filt to demangle the C++ symbol names.
Before:
```
...
40072f5c <_ZN6tflite21reference_integer_ops17ConvPerChannel4x4ERKNS_10ConvParamsEPKlS5_RKNS_12RuntimeShapeEPKaS8_SA_S8_S5_S8_Pa>:
40072f5c:       f7010113                addi      sp,sp,-144
40072f60:       0006a883                lw        a7,0(a3)
40072f64:       00068e13                mv        t3,a3
...
40073178:       3ef7860b                cfu[31,0]  a2, a5, a5
4007317c:       60f7960b                cfu[48,1]  a2, a5, a5
40073180:       00170713                addi      a4,a4,1
40073184:       00c686b3                add       a3,a3,a2
40073188:       fe8718e3 …
```

demangle C++ symbols in disassembler dumps

---

proj/hps_accel/src/blocks_test.cc

This line was accidentally dropped in commit 7fd3e19a. We need it due to
commit 8f308c35.

hps_accel: fix the on-device tests for the macc unit

---

soc/hps_soc.py

This is currently the fastest mode we can achieve. rate='1:2' is not working yet. READ_1_4_4 is not working yet.

hps: update SPI flash to READ_1_1_4 with divisor 0

---

conf/environment.yml

Remove pin from nextpnr-nexus since default 'main' is now correct.

---

common/renode-verilator-integration/sim_main.cpp
docs/source/step-by-step.rst
proj/example_cfu_v/cfu.v
proj/kws_micro_accel/cfu.sv
proj/proj_template_v/cfu.v
python/nmigen_cfu/cfu.py
python/nmigen_cfu/test_cfu.py
soc/cfu/Cfu.v

Since https://github.com/enjoy-digital/litex/pull/1039 was merged, remove all mentions and instances of this signal from the documentation and source code.

Remove all instances of the payload_response_ok signal

---

soc/hps.mk
soc/hps_proto2_platform.py

This is the configuration I am using to get numbers in our tracking spreadsheet.
Alan, you may prefer to keep the parallel router2 runs by default? I found it unnecessary but maybe it gives better results? I note that the parallel-nextpnr script doesn't look for a seed that gives the *best* result, just whichever one completes first.

hps: router1, no abc9, 64MHz

---

proj/hps_accel/Makefile

This buys us a lot more breathing room in terms of avoiding FPGA
congestion, at a cost of about 35% slower model evaluation time.

hps_accel: use slim CPU

---

common/Makefile

This PR modifies the Makefile used for building software to sort found sources.
This ensures that the object files will be linked in the same order on all machines - without that binaries built on different hosts can get different model evaluation times.

common/Makefile: sort find output

---

.github/workflows/fomu.yml
common/Makefile
conf/environment.yml
conf/requirements.txt

add Fomu GHA that uses new conda-provided gcc.

Add ice40 and riscv toolchain support to the conda env;

---

soc/hps.mk

Restore the use of -abc9 with the HPS platform.

---

docs/requirements.txt

Trying to fix breakage in CI due to docutils 0.18 incompatibility.

docs: upgrade to Sphinx 4.3

---

docs/source/setup-guide.rst
scripts/setup

Eventually we'll just use conda but in the meantime, update it.

docs: recommend Sifive August 2020 toolchain

---

common/_hps/hps/ld/linker.ld
common/src/tflite.cc
soc/hps_soc.py

To use, add this to your make command:
EXTRA_LITEX_ARGS="--separate-arena"
Tested on proto2 both with and without this new option.

Update software/linker to use separate tensor arena region.

---

.github/workflows/sync-tflm.yml
conf/requirements.txt
proj/hps_accel/renode/hps.repl
scripts/setup
scripts/sync_from_tflite_micro.sh

This PR should be merged after #343. It introduces new CI workflow that checks if there are any updates possible to apply on `third_party/tflite-micro`.
It also adds a script to update it manually. It is also included in `scripts/setup` so running a setup will also update `tflite-micro`. If there is already existing `third_party/tflite-micro` setup script will prompt a warning to not override an existing one. If user decides to remove it, then setup script will get the latest version.
Current TF Lite Micro version used by CFU Playground will be stored in `conf/tflite-micro.version`.
Since this was tested on Antmicro's fork, there is an Antmicro's bot account set up in CI. You can either let me know what should be a name and email of an account for CFU Playground or you can merge this PR …

Add CI that automatically updates `third_party/tflite-micro`

---

.github/workflows/oxide.yml
proj/mport/Makefile
proj/mport/cfu.v
proj/mport/src/README.md
proj/mport/src/proj_menu.cc
proj/mport/src/software_cfu.cc
soc/board_specific_workflows/general.py
soc/hps_lattice_nx.py
soc/hps_soc.py

Update: I added a project (`proj/mport`) to test the new functionality.  It is tested in CI by the `oxide.yml` workflow.   In that flow I added doing the software compile, which encountered a clash of GCCs as expected (#365), so I removed the SiFive 8.3 toolchain download (there's still more to do for #365).
To enable all of the functionality added in this PR, you need to add both `--separate-arena` and `--cfu-mport` to your Litex flags.   This is already done in the Makefile in `proj/mport`.

Expose 2nd LRAM ports; connect to CFU; testcase.

---

proj/proj.mk

Fomu requires a second or so after the upload
for the tty to appear at /dev/ttyACM0.
Also add a "connect" target that does just that
(doesn't build anything).

Add a pause before connecting to the board. Helps Fomu.

---

proj/hps_accel/src/hps_cfu.h

Adds cfu_setx() which had been omitted. Adding this allows the build to
succeed.

hps_accel/hps_cfu.h: add cfu_setx()

---

common/_sim/sim/ld/linker.ld
soc/sim.mk
soc/sim.py

Also fills in some missing sim support, e.g. handling custom VexRiscv variants.

Update Verilator sim to handle dual-port arena

---

.github/workflows/test-projects.yml

This will save a lot of bandwidth and possibly speed up the whole CI process
I mark it as a draft, as it's still using Renode action from a branch. As soon as we merge it, I'll update this PR

Use cache for Renode downloading in CI

---

soc/hps_proto2_platform.py
soc/hps_soc.py

Fixes slew rate on IO pins issue to allow the SPI flash to reliably run
at full speed. Also uses DDR clocking on SPI flash. This reduces
HPS 09_20 evalation times by approximately 1M cycles.

soc/hps_*.py: Fix slew rate and DDR clock

---

common/Makefile
common/_hps/hps/ld/linker.ld

Fixes large data in address space. This makes loading programs onto
proto2 faster since these data structures do not need to be updated if
they have not changed.

hps/linker.ld: Fix large data address

---

.github/workflows/sync-renode.yml
.github/workflows/sync-tflm.yml

This should allow us to create automergable PRs and help us pass the CLA
wall.

ci: Autobump Renode and TFLM with Personal Access Token

---

.github/workflows/fmax-trials-fresh-build.yml
.github/workflows/fmax-trials.yml
.github/workflows/oxide.yml
.gitignore
scripts/custom-nextpnr-nexus
soc/hps_proto2_platform.py
soc/hps_soc.py

This PR adds the possibility to use a different build template that can be used to pass additional parameters to nextpnr
With some experimentation performed using [FPGA tool perf](https://github.com/SymbiFlow/fpga-tool-perf)'s ability to run a set of builds using different combinations of input parameters, one combination among others yielded good results (locally) both in terms of runtime and max frequency was the following:
```
placer-heap-beta: 0.5 (default)
placer-heap-alpha: 0.1 (default)
placer-heap-critexp: 0.7 (default)
placer-heap-timingweight: 52 (custom)
```

Add custom nextpnr params

---

.github/workflows/sync-renode.yml

Now the `git commit` really will only be executed when the new version
is available.
When Renode is up to date:
* the CI job will finish with a success status,
* the `create-pr` step won't start,
* a clear notice with such an information will be printed in the CI run.
Signed-off-by: Adam Jeliński <ajelinski@antmicro.com>

CI: sync-renode: Fix the up-to-date behavior

---

scripts/parallel-nextpnr-nexus

Uses the incoming seed as the first seed rather then always starting
from 1000.

parallel-nextpnr-nexus: better seed handling

---

proj/hps_accel/Makefile
proj/hps_accel/cfu_gen.py
proj/hps_accel/gateware/gen2/accelerator.py
proj/hps_accel/gateware/gen2/hps_cfu.py
proj/hps_accel/gateware/gen2/macc.py
proj/hps_accel/gateware/gen2/sysarray.py
proj/hps_accel/gateware/gen2/test_macc.py

Builds on #433 to ensure unit tests pass while allowing the use of the DSP macro when building for Crosslink NX.

Wraps: Manually instantiated MULTADDSUB9X9WIDE in MaccBlock to save resources.

---

proj/hps_accel/gateware/gen2/macc.py

This PR adds manual instances of the `MULTADDSUB9X9WIDE` for `MaccBlock`. That macro maps directly to the module architecture, with it we can almost completely remove all generic LUTs and FFs currently needed.
The change requires nextpnr with this fix https://github.com/YosysHQ/nextpnr/pull/899 and results in a working design in hardware.
There are two issues here:
- Tests for systolic array fail - nMigen/Amaranth cannot simulate behavior of the DSP macro instance.
- If the design is to be targeted for multiple architectures there has to be conditional generation so that the macro is used only for Nexus.

[WIP] Use MULTADDSUB9X9WIDE for MaccBlock

---

soc/hps_soc.py

Turn off LED chaser by default, without removing entirely.

---

proj/hps_accel/Makefile
proj/proj.mk
soc/hps.mk
soc/hps_soc.py

This PR does the following:
- adds an additional argument for the HPS SoC to control whether the BIOS needs to be built. The default behavior is to not build the BIOS, therefore removing the unnecessary `timer0`, saving up a couple hundreds of LUTs and FFs.
- Adds the `--no-compile-software` flag when building the bitstream. CSRs are still being output, and they are also relevant only when building software. Given that changes either to the gateware or software in terms of CSR requires building both of them, it should be alwasy the case to first do `make clean` and than `make bitstream software`. 
- Adds possibility to build the HPS software parallely by adding the `BUILD_JOBS=<n jobs>` when running `make software`
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

hps: allow removing timer by not building BIOS code

---

docs/source/setup-guide.rst

Add note about symbiflow route and place tools not completing if
unable to meet timing. This will be likely to occur using the
suggested Arty A7 when completing the Test Run in Step 6 of the
Setup Guide. As this can be confusing for new users, this change
suggests the user can add the command to lower the target clock
rate when completing this step if required.

Update Setup Guide for Arty A7 using Symbiflow

---

soc/patch_cpu_variant.py
soc/vexriscv/Makefile
soc/vexriscv/VexRiscv_HpsCfu.v
soc/vexriscv/VexRiscv_HpsCfu.yaml
soc/vexriscv/VexRiscv_HpsdeltaCfu.v
soc/vexriscv/VexRiscv_HpsdeltaCfu.yaml

"hps+cfu" is the same as "slim+cfu" but with reduced CSRs.
"hpsdelta+cfu" is meant for experimentation; currently is has a larger (4kB) I-cache than "hps+cfu".   Its cycle count per inference is reduced by about 2%, and it also seems to be able to achieve 90MHz+ more easily than "hps+cfu".

Add new VexRiscv variants "hps+cfu" and "hpsdelta+cfu".

---

soc/hps_proto2_platform.py

The current version of Crosslink-NX Family Data Sheet lists the high
frequency oscillator maximum frequency as 481.5MHz (that is, 7% higher
than its nominal 450MHz):
https://www.latticesemi.com/-/media/LatticeSemi/Documents/DataSheets/CrossLink/FPGA-DS-02049-1-2-1-CrossLink-NX-Family.ashx?document_id=52780
Older documents listed a wider frequency range but ±7% is the range for
production parts.

hps: reduce OSCA worst case to 7%

---

.github/workflows/sync-renode.yml
.github/workflows/sync-tflm.yml

It turned out that detecting if you are a fork in runtime is hell, but there's a convenient check we might have. It has a hardcoded "google" string, so please let me know if it's ok

Filter the sync workflows to only run on the main repo

---

conf/environment.yml

(required for some upcoming Lattice Nexus optimizations)

Add SymbiFlow Yosys plugins even for non-Xilinx env.

---

common/Makefile

The hardcoded "-march=rv32im" would be wrong if we try
using compressed or floating point extensions.

Use LiteX-generated $CPUFLAGS instead of hardcoded flags.

---

proj/hps_accel/Makefile
soc/vexriscv/Makefile
soc/vexriscv/VexRiscv_HpsCfu.v
soc/vexriscv/VexRiscv_HpsCfu.yaml

8% register reduction, 4% LUT reduction, 1.5% better fmax avg.

Use new "hps" variant with fewer CSRs.

---

soc/hps_proto2_platform.py

This PR fixes https://github.com/google/CFU-Playground/issues/499 by writing JSON again under the same name after DSP register inference.

Writing JSON file after DSP register inference

---

common/_hps/hps/ld/linker.ld
proj/example_cfu/Makefile

HPS tests were failing with the latest tflite-micro bump (https://github.com/google/CFU-Playground/pull/500#issuecomment-1075741023).   With local testing, I observed the same thing also on `main` branch, which is a bit puzzling.   This is the error (the exact value can vary):
```
/home/runner/work/CFU-Playground/CFU-Playground/proj/example_cfu/build/ld/linker.ld:27
cannot move location counter backwards (from 00000000202803f0 to 0000000020280000)
```
To reproduce the previous behavior locally,
```
cd proj/example_cfu
make PLATFORM=hps BUILD_JOBS=8 software
```
Edit: Another mystery -- the symptom only occurs eith `example_cfu` -- not with `proj_accel_1`, `mnv2_first`, `hps_accel`, or the  template projects.    I haven't found what the difference is.
Edit#2: Solved!   All of the other …

Expand space for .text section from 0x80000 to 0x81000 on HPS platform

---

soc/board_specific_workflows/general.py
soc/patch_cpu_variant.py

Prototype code for generating a VexRiscv variant on demand.   To trigger, just use any unrecognized variant, for example, add this to the project Makefile:
```
export EXTRA_LITEX_ARGS
EXTRA_LITEX_ARGS += --cpu-variant doesnotexist+cfu
```
The current code ignores the variant and just builds a vanilla VexRiscv.   More code needs to be added to parse the variant string to generate the config and the corresponding canonical Verilog file name.

Initial code for building customized VexRiscv on-demand.

---

soc/board_specific_workflows/digilent_arty.py

This PR changes the default target frequency for the Arty A7 board to 75MHz when SymbiFlow is used.   It can still be overridden by an explicit `--sys-clk-freq` LiteX option to be either higher or lower.
The default frequency for an Arty A7 board in litex-boards is 100MHz.  When the bitstream is built with this target frequency, vpr will not meet timing, but it will not give visible error, and a bitstream will be generated.   The bitstream will not work on the board; the LEDChaser works, but loading and running software over UART does not work (see #455).
There is an open issue for vpr to produce a hard error when it does not meet timing (https://github.com/verilog-to-routing/vtr-verilog-to-routing/issues/1928).   However, here we would need to downgrade the error, since with even a …

Make Arty default clk freq 75MHz when using SymbiFlow.

---

.gitignore

conf/requirements.txt and conf/environment.yml are updated by `make
sf-install`. `git status` then records them as modified, but the
developer mostly likely does not want to send these updates upstream.
This change adds these two files to .gitignore.

conf: ignore files updated by Symbiflow install

---

proj/proj.mk

Set default software build parallelism to `nproc`.

---

.github/workflows/symbiflow.yml
.gitignore
Makefile
conf/environment-symbiflow.yml

One for Lattice, one for Xilinx (SymbiFlow).

Remove conda hackery.  Now support 2 different conda envs.

---

scripts/install_oxide

Contains two fixes:
1. Passes full path to Yosys src the plugin make command, which enables
it to find the yosys-config script.
2. Passes DESTDIR to the first yosys make invocation so that it can be
used when constructing the yosys-config script.
Note that the install_oxide script will require a change to the yosys
makefile in order to construct the correct yosys-config script.

scripts/install_oxide: fixes

---

scripts/install_oxide

Updates build commands for Yosys, Yosys plugins and Nextpnr to inform
the builds of the final installation directory, under
third_party/usr/local.
In particular,
- for Yosys, replaces use of "DESTDIR=foo", with "PREFIX=foo".
- for Nextpnr, set CMAKE_INSTALL_PREFIX to specify from where the built
binaries will run.

scripts/install_oxide: set installation paths

---

soc/board_specific_workflows/ice40up5k.py
soc/patch_cpu_variant.py

Before, the patching for the fomu cpu variant was only done
when you were targeting the fomu board.  This change
makes it so the patching is always done, so that the fomu
variant is always available, including in Verilator sim.
This fixes #543.

Make 'fomu' cpu variant available everywhere incl. sim.

---

common/src/menu.cc
proj/skip_tflm/Makefile

* Remove model include lines from "skip_tflm" proj Makefile
* Ignore CR/LF in menu input (these are necessarily added
when running Renode in the Colab; this tidies things up,
preventing spurious *unknown* messages).

Some cleanup:

---

common/src/main.c
soc/vexriscv/Makefile
soc/vexriscv/VexRiscv_Fomu.v
soc/vexriscv/VexRiscv_FomuCfu.v
soc/vexriscv/src/main/scala/vexriscv/GenCoreDefault.scala

This allows Vex+CFU to fit onto Fomu.
We used to need this to catch unexexpected 'div'
instructions in the binary (even though we compiled with
--no-div).  But we no longer have this issue.

(VexRiscv) Don't implement HW to catch illegal instructions.

---

scripts/install_oxide

The dsp-ff plugin Makefile now has building a directory
as the default action, which isn't enough, so we must
now explicitly "make all" instead of just "make".
It is currently broken either in CI or if you're running 
`./scripts/install_oxide` locally.

Fix install_oxide script w.r.t. dsp-ff plugin

---

proj/hps_accel/gateware/gen2/accelerator.py

This shortens a long path and allows model eval to function correctly
when div=5.
Signed-off-by: David Lattimore <dml@google.com>

hps_accel: Latch output of adding input_offset

---

.github/workflows/symbiflow.yml
Makefile

Note: SymbiFlow installation is broken both before and after this change, but this is a step in the right direction.

Update urls for SymbiFlow/F4PGA installation tars.

---

soc/hps_proto2_platform.py

When I was porting the dynamic clock control change (PR #597) to ChromeOS:
https://chromium-review.googlesource.com/c/chromiumos/platform/hps-firmware/+/3783309
I found that I needed to connect the sys clock domain's reset signal to the osc clock domain's reset signal. Otherwise it doesn't seem to come out of reset properly.
I'm not sure why we got away without this in CFU-Playground, but let's add it here for consistency too.

hps: drive sys reset signal from osc reset signal

---

common/src/models/models.h

This PR fixes a bug in some legacy code to make sure compilation succeeds. If no TFLM models are included in the project makefile by commenting out this [line](https://github.com/google/CFU-Playground/blob/fc6f7991f9618c4b694b3ef2b4716f31e3c19469/proj/proj_template/Makefile#L29), the following [code](https://github.com/google/CFU-Playground/blob/fc6f7991f9618c4b694b3ef2b4716f31e3c19469/common/src/models/models.c#L74-L76) will be included in compilation. However, the build fails if you comment out the PDIT8 model with the following error:
```
…
LD       software.elf
/home/shvetank/Repos/CFU-Playground/env/conda/envs/cfu-symbiflow/bin/../lib/gcc/riscv32-elf/10.1.0/../../../../riscv32-elf/bin/ld: src/models/models.o: in function `.LANCHOR0':
models.c:(.sdata.MENU+0x10): undefined reference …
```

Fix compilation if no TFLM models included in Makefile

---

common/src/models/models.h

This change causes problems; I think it makes the model version of `no_menu` more visible so that it clashes with the embench version of `no_menu`.
If you do this:
```
% cd proj/proj_template_v
% make software
```
you will get:
```
...
CXX tflite_unit_tests.cc      tflite_unit_tests.o
AS  crt0-vexriscv.S   crt0-vexriscv.o
LD       software.elf
/media/tim/GIT/tcal-x/CFU-Playground/env/conda/envs/cfu-common/bin/../lib/gcc/riscv32-elf/10.1.0/../../../../riscv32-elf/bin/ld: src/third_party/embench_iot_v1/embench.o: in function `no_menu':
/media/tim/GIT/tcal-x/CFU-Playground/proj/proj_template_v/build/src/third_party/embench_iot_v1/embench.c:23: multiple definition of `no_menu'; src/models/models.o:/media/tim/GIT/tcal-x/CFU-Playground/proj/proj_template_v/build/src/models/models.c:32: first …
```

Revert "Fix compilation if no TFLM models included in Makefile"

---

conf/environment-symbiflow.yml
conf/environment.yml

I think they used to be implicitly loaded as dependencies of the Verilator package, but now they need to be explicitly specified.

Add json-c and libevent to conda env.

---

Makefile

FOR FUTURE REFERENCE: To update F4PGA in CFU-Playground, update the top `Makefile` to correspond to any changes in the instructions on this page: https://f4pga-examples.readthedocs.io/en/latest/getting.html
(Usually it's just updating `F4PGA_TIMESTAMP` and `F4PGA_HASH`, but in this case one of the tar paths also changed.)

Update for F4PGA installation.

---

soc/vexriscv/Makefile
soc/vexriscv/VexRiscv_Custom.v
soc/vexriscv/VexRiscv_CustomCfu.v
soc/vexriscv/VexRiscv_Fomu.v
soc/vexriscv/VexRiscv_FomuCfu.v
soc/vexriscv/VexRiscv_Fpu.v
soc/vexriscv/VexRiscv_FpuCfu.v
soc/vexriscv/VexRiscv_HpsCfu.v
soc/vexriscv/VexRiscv_HpsdeltaCfu.v
soc/vexriscv/VexRiscv_MinCfu.v
soc/vexriscv/VexRiscv_PerfCfu.v
soc/vexriscv/VexRiscv_PerfCfuDebug.v
soc/vexriscv/VexRiscv_SlimCfu.v
soc/vexriscv/VexRiscv_SlimCfuDebug.v
soc/vexriscv/VexRiscv_SlimPerfCfu.v
soc/vexriscv/VexRiscv_SlimPerfCfuDebug.v
soc/vexriscv/VexRiscv_SlimoptCfu.v
soc/vexriscv/VexRiscv_dbpl8Cfu.v
soc/vexriscv/src/main/scala/vexriscv/GenCoreDefault.scala

VexRiscv build script updated and all verilog files rebuilt.  Makefile fixed (added missing verilog targets).
Now at tip of master of the VexRiscv.  The issue of #596 is avoided by configuring the CfuPlugin with "withEnable = false".     See also https://github.com/SpinalHDL/VexRiscv/issues/258.
This also incorporates a change to add the attribute   `(* no_rw_check *)`  on the block memories in VexRiscv --     regfile and caches.   This prevents Yosys from adding circuitry for a check that we don't need, according to Charles P.    Having the check consumes resources, particularly noticeable     when targetting ice40.

Update VexRiscv: no rw check on blockmem; work around #596 (CFU CSR collision)

---

scripts/setup

It isn't available in Debian and Ubuntu docker containers by default.
Signed-off-by: Adam Jeliński <ajelinski@antmicro.com>

scripts/setup: Use `sudo` only if available

---

common/src/main.c
proj/proj.mk
proj/proj_template/Makefile
proj/proj_template_v/Makefile
proj/skip_tflm/Makefile
third_party/litex-donut/LICENSE
third_party/litex-donut/README
third_party/litex-donut/donut.c
third_party/litex-donut/donut.h

It is enabled in projects `skip_tflm`, `proj_template`, and `proj_template_v`.
It *can* be enabled in any project.

Add 'donut' demo from LiteX.

---

soc/board_specific_workflows/digilent_arty.py
soc/board_specific_workflows/test_digilent_arty.py

It had been disabled (L2 cache size had been forced to 8kB).

Re-enable L2 cache size option `--l2-size`.

---

scripts/fix_cfu_dis.py

Optionally match a leading space, which has been added to the output from 'objdump -d'.  
Fixes #687.

Update script for patching disassembly for CFU instructions.

---

soc/vexriscv/README.md

Made addition to README documentation specifying how to generate a Vexriscv variant on demand from the command line.

Add notes for vexriscv on demand build

---

scripts/setup

Pin downloads from renode/renode-infrastructure
to a particular commit before a change that breaks Renode sim here (issue #805).
This fixes #805.

Pin downloads from renode/renode-infrastructure

---

Makefile
conf/environment-symbiflow.yml
conf/environment.yml

Pin the Yosys package to a version compatible with the F4PGA Yosys plugins.
This fixes #808.
Tested: manually built the bitstream and tested it on an Arty 35T board with the CFU Playground firmware.
When the plugins package updates, we can unpin Yosys.
Also, comment out the download of the xc7a200t database to make the installation of F4PGA faster.
**NOTE**: After you sync to this update, you don't need to reinstall the entire Symbiflow/F4PGA environment.   Just do this (while not *inside* the environment, at the root directory of the CFU-Playground repo):
```
make USE_SYMBIFLOW=1 env
```
Then enter the Symbiflow/F4PGA environment and use:
```
make enter-sf
cd proj/proj_template_v
make USE_SYMBIFLOW=1 bitstream
```

Pin the Yosys package to a version compatible with the F4PGA plugins

---

conf/environment-symbiflow.yml
conf/environment.yml

Workaround for https://github.com/YosysHQ/yosys/issues/4081.
This issue is specific to the Lattice Nexus flow.
With current Yosys, the synthesized netlist from `synth_nexus` contains an explicit 1'b0 driving the low order CIN of a chain of CCU2 (carry chain) primitives.  This causes a `nextpnr-nexus` error.    `nextpnr-nexus` expects this input to be undriven which I assume implies an implicit 1'b0 input.

Pin Yosys back to 0.29 as workaround for Nexus flow (Yosys #4081).
